<?php
/*
 * 订单管理
 * @author     Mrlv(315141428@qq.com)
 * @copyright  上海比良网络科技有限公司
 * @Created    2017-11-26
 */
namespace addons\weshop\controller;
use addons\weshop\model\Weshop_type;
use addons\weshop\model\Weshop_goods;
use addons\weshop\model\Weshop_address;
use addons\weshop\model\Weshop_order;
use addons\weshop\model\Payment;
use addons\weshop\model\Weshop_comment;
use app\common\controller\Addon;
use think\Controller;
use think\facade\Request;
class Order extends Addon
{
    public $adminLogin=true;//需要管理员登录才可操作本控制器
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub        
    }

    public function index(){
        $model = new Weshop_order();        
        $result=$model
            ->where(['mpid'=>$this->mid])
            ->order('time DESC')
            ->paginate(20);
        $goodsIdList = $paymentIdList = $addressIdList = array();
        foreach ($result as $key => $value) {
            $goodsIds           = json_decode($value['goods_id'],true);
            foreach ($goodsIds as $gkey => $gvalue) {
                array_push($goodsIdList, $gvalue[0]);
            }            
            $paymentIdList[]    = $value['payment_id'];
            $addressIdList[]    = $value['address_id'];
        }
        $goodsInfo      = $this->getGoodsInfo($goodsIdList);
        $paymentInfo    = $this->getPaymentInfo($paymentIdList);
        $addressInfo    = $this->getAddressInfo($addressIdList);

        foreach ($result as $key => &$value) {
            $goodsInfoArr = array();
            $goodsIds       = json_decode($value['goods_id'],true);
            foreach ($goodsIds as $gkey => $gvalue) {
                if(isset($goodsInfo[$gvalue[0]])){
                	$goodsInfo[$gvalue[0]]['count'] = $gvalue[1];
                    array_push($goodsInfoArr, $goodsInfo[$gvalue[0]]);
                }
            }
            $value['goodsInfo']    = $goodsInfoArr;
            $value['paymentInfo']  = isset($paymentInfo[$value['payment_id']]) ? $paymentInfo[$value['payment_id']]: array();
            $value['address_info'] = isset($addressInfo[$value['address_id']]) ? $addressInfo[$value['address_id']]: array(); 
            $value['is_comment']   = $this->getComment($value['id']);           
        }

        $this->assign('data',$result);
        $this->fetch();
    }

    //评价详情
    public function getComment($id){
        $returnData = 0;        
        $model = new Weshop_comment();  
        $commentRow = $model->where('mpid',$this->mid)->where('order_id',$id)->find();
        if ($commentRow) {
            $returnData = 1;
        }        
        return $returnData;
    }

    //商品详情
    public function send(){
    	if(Request::isAjax()){ 
    		$id 	= input('id');
            $company 		= input('company');    
            $logistics_num 	= input('logistics_num');              
            $model = new Weshop_order();        
            $result=$model
                ->where(['mpid'=>$this->mid,'id'=>$id])
                ->find();                        
            if($result){
                $model
                ->where(['mpid'=>$this->mid,'id'=>$id])
                ->update(['company'=>$company,'logistics_num'=>$logistics_num,'is_send'=>1]);
                ajaxReturn(null, 1, '操作成功');
            }else{
                ajaxReturn(null, 0, '数据不存在');
            }
        }else{
            $id 	= input('id');
	    	$model 	= new Weshop_order();
	    	$row 	= $model->where('mpid',$this->mid)->where('id',$id)->find();
	    	$this->assign('row',$row);
	        $this->fetch(); 
        }    	       
    }

    //商品详情
    public function getGoodsInfo($goodsIdList=array()){
        $returnData = array();
        if(!empty($goodsIdList)){
            $model = new Weshop_goods();  
            $goodsList = $model->where('mpid',$this->mid)->where('id','in',$goodsIdList)->select();
            foreach ($goodsList as $key => $value) {
                $returnData[$value['id']] = $value;
            }
        }
        return $returnData;
    }

    //支付详情
    public function getPaymentInfo($paymentIdList=array()){
        $returnData = array();
        if(!empty($paymentIdList)){
            $model = new Payment();  
            $paymentList = $model->where('mpid',$this->mid)->where('payment_id','in',$paymentIdList)->select();
            foreach ($paymentList as $key => $value) {
                $returnData[$value['payment_id']] = $value;
            }
        }
        return $returnData;
    }
    //地址详情
    public function getAddressInfo($addressIdList=array()){
        $returnData = array();
        if(!empty($addressIdList)){
            $model = new Weshop_address();  
            $addressList = $model->where('mpid',$this->mid)->where('id','in',$addressIdList)->select();
            foreach ($addressList as $key => $value) {
                $returnData[$value['id']] = $value;
            }
        }
        return $returnData;
    }

    public function edit(){
        $datamodel = new Weshop_order();                  
        $result=$datamodel                
                ->where(['mpid'=>$this->mid])
                ->find();
        if(Request::isAjax()){ 
            $id = input('id');               
            if($result){
                $datamodel
                ->where(['mpid'=>$this->mid,'id'=>$id])
                ->update(['remark'=>input('remark'),'status'=>input('status')]);
                ajaxReturn(null, 1, '操作成功');
            }else{
                $datamodel
                ->insert(['remark'=>input('remark'),'mpid'=>$this->mid,'status'=>input('status')]);
                ajaxReturn(null, 1, '操作成功');
            }     
        } 
        $this->assign('data',$result);
        $this->fetch();
    }

    public function del(){
        if(Request::isAjax()){ 
            $id = input('id');            
            $model = new Weshop_order();        
            $result=$model
                ->where(['mpid'=>$this->mid,'id'=>$id])
                ->find();                        
            if($result){
                $model
                ->where(['mpid'=>$this->mid,'id'=>$id])
                ->delete();
                ajaxReturn(null, 1, '操作成功');
            }else{
                ajaxReturn(null, 0, '数据不存在');
            }
        }else{
            ajaxReturn(null, 0, '数据不存在');
        }
    }  
}