<?php
/*
 * 商品分类
 * @author     Mrlv(315141428@qq.com)
 * @copyright  上海比良网络科技有限公司
 * @Created    2017-11-26
 */
namespace addons\weshop\controller;
use addons\weshop\model\Weshop_type;
use app\common\controller\Addon;
use think\Controller;
use think\facade\Request;
class Type extends Addon
{
    public $adminLogin=true;//需要管理员登录才可操作本控制器
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub        
    }    

    public function index(){
        $model = new Weshop_type();        
        $result=$model
            ->where(['mpid'=>$this->mid])
            ->order('sort DESC')
            ->paginate(20);
        $this->assign('data',$result);
        $this->fetch();
    }

    public function edit(){
        $datamodel = new Weshop_type();
        $id = input('id');
        $result = array();
        if(isset($id)){              
            $result=$datamodel                
                ->where(['mpid'=>$this->mid,'id'=>$id])
                ->find();
        } 
        if(Request::isAjax()){                
            if($result){
                $datamodel
                ->where(['mpid'=>$this->mid,'id'=>$id])
                ->update(['title'=>input('title'),'sort'=>input('sort'),'icon'=>input('icon')]);
                ajaxReturn(null, 1, '操作成功');
            }else{
                $datamodel->insert(['mpid'=>$this->mid,'title'=>input('title'),'sort'=>input('sort'),'icon'=>input('icon')]);
                ajaxReturn(null, 1, '操作成功');
            }     
        }
        $this->assign('data',$result);
        $this->fetch();
    }

    public function del(){
        if(Request::isAjax()){ 
            $id = input('id');            
            $model = new Weshop_type();        
            $result=$model
                ->where(['mpid'=>$this->mid,'id'=>$id])
                ->find();                        
            if($result){
                $model
                ->where(['mpid'=>$this->mid,'id'=>$id])
                ->delete();
                ajaxReturn(null, 1, '操作成功');
            }else{
                ajaxReturn(null, 0, '数据不存在');
            }
        }else{
            ajaxReturn(null, 0, '数据不存在');
        }
    }    
}